### ISSUE TITLE
[create_elf] KeyError: '.iram0.text'

### ISSUE THREAD

**Issue by josesa** [tenable/esp32_image_parser#14]
Getting the following errors on a binary 

```
Dumping partition 'ota_0' to ota_0_out.bin
Unsure what to do with segment: PADDING
Unsure what to do with segment: RTC_DATA
Traceback (most recent call last):
  File "esp32_image_parser.py", line 283, in <module>
    main()
  File "esp32_image_parser.py", line 266, in main
    image2elf(dump_file, output_file, verbose)
  File "esp32_image_parser.py", line 159, in image2elf
    size = len(section_data['.iram0.vectors']['data']) + len(section_data['.iram0.text']['data'])
                                                             ~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: '.iram0.text'
```

**Comment by niftic** [comment]
Might get fixed by #15

**Comment by helgek** [comment]
It does fix the issue, thank you!

**Comment by helgek** [comment]
All the three fixes I needed to eventually create the .elf file are included in this version:

[esp32_image_parser.zip](https://github.com/tenable/esp32_image_parser/files/14895309/esp32_image_parser.zip)
