### ISSUE TITLE
[Create Elf] Error

### ISSUE THREAD

**Issue by TonyMahagony39** [tenable/esp32_image_parser#16]
Hi,

I get the following error when I want to create an ELF, the command I write is:

 python.exe esp32_image_parser.py create_elf fw-backup-4M.bin -partition factory -output factory.elf

The error is:

Dumping partition 'factory' to factory_out.bin
Traceback (most recent call last):
  File "esp32_image_parser.py", line 281, in <module>
    main()
  File "esp32_image_parser.py", line 264, in main
    image2elf(dump_file, output_file, verbose)
  File "esp32_image_parser.py", line 41, in image2elf
    image = LoadFirmwareImage('esp32', filename)
NameError: name 'LoadFirmwareImage' is not defined

Do you know what could be the problem?

**Comment by mid-kid** [comment]
Hit this same issue, thankfully I can just load it manually, but still a shame to see this functionality broken.

**Comment by razvanphp** [comment]
Fixed in #11, duplicate of #4
