### ISSUE TITLE
name 'LoadFirmwareImage' is not defined

### ISSUE THREAD

**Issue by cryptax** [tenable/esp32_image_parser#4]
I get this error when I try to dump a partition:

```
./esp32_image_parser.py create_elf flash.bin -partition app0 -output app0.elf
Dumping partition 'app0' to app0_out.bin
Traceback (most recent call last):
  File "softs/esp32_image_parser/./esp32_image_parser.py", line 281, in <module>
    main()
  File "softs/esp32_image_parser/./esp32_image_parser.py", line 264, in main
    image2elf(dump_file, output_file, verbose)
  File "softs/esp32_image_parser/./esp32_image_parser.py", line 41, in image2elf
    image = LoadFirmwareImage('esp32', filename)
NameError: name 'LoadFirmwareImage' is not defined
```

This can be fixed in `esp32_image_parser.py` if you add `from esptool.bin_image import *`:

```python
import sys
import json
import os, argparse
from makeelf.elf import *
from esptool import *
from esptool.bin_image import *
from esp32_firmware_reader import *
from read_nvs import *
...
```

**Comment by leakerlee** [comment]
thx

**Comment by h4sh5** [comment]
can you make a PR for this? just so everyone's got the fix

**Comment by ladderlogix** [comment]
thank
