### ISSUE TITLE
KeyError '.dram0.data'`

### ISSUE THREAD

**Issue by cfficaurzua** [tenable/esp32_image_parser#7]
I got this error. any help will be appreciated. 

```
PS D:\Development\esp decompiler\esp32_image_parser> python ./esp32_image_parser.py create_elf  firmware_before_corruption.bin -partition ota_0 -output output.elf  
Dumping partition 'ota_0' to ota_0_out.bin
Unsure what to do with segment: BYTE_ACCESSIBLE, DRAM
Traceback (most recent call last):
  File "./esp32_image_parser.py", line 282, in <module>
    main()
  File "./esp32_image_parser.py", line 265, in main
    image2elf(dump_file, output_file, verbose)
  File "./esp32_image_parser.py", line 160, in image2elf
    size = len(section_data[name]['data'])
KeyError: '.dram0.data'
```

**Comment by srinidhigithub** [comment]
section_map = {
        'DROM'                      : '.flash.rodata',
        'BYTE_ACCESSIBLE, DRAM, DMA': '.dram0.data',
        #
        'BYTE_ACCESSIBLE, DRAM': '.dram0.data',
        #
        'IROM'                      : '.flash.text',

**Comment by cfficaurzua** [comment]
it worked thanks.
