### ISSUE TITLE
KeyError: '.dram0.data'

### ISSUE THREAD

**Issue by jithivk** [tenable/esp32_image_parser#8]
Dumping partition 'app0' to app0_out.bin
Unsure what to do with segment: BYTE_ACCESSIBLE, DRAM
Unsure what to do with segment: RTC_IRAM
Traceback (most recent call last):
  File "C:\Desktop\esp32_image_parser-master\esp32_image_parser.py", line 282, in <module>
    main()
  File "C:\Desktop\esp32_image_parser-master\esp32_image_parser.py", line 265, in main
    image2elf(dump_file, output_file, verbose)
  File "C:\Desktop\esp32_image_parser-master\esp32_image_parser.py", line 160, in image2elf
    size = len(section_data[name]['data'])
KeyError: '.dram0.data'

**Comment by jithivk** [comment]
solved the issue.

**Comment by SaschaDens** [comment]
For those that also want to know how @jithivk solved it can check the PR #3, which resolved the issue also for me 😄.

**Comment by Neuromantestd** [comment]
> For those that also want to know how @jithivk solved it can check the PR #3, which resolved the issue also for me smile.

Correct me if I'm wrong, but, the solution then is using a esptool version that includes `LoadFirmwareImage`?

**Comment by darknetv** [comment]
Use Esptool version 2.8. solved it
